name: OMNITRADE Operations
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15241
title: OMNITRADE Operations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#629fe9'
    - '#87c5fe'
    - '#004086'
    - '#2961a6'
  brandStrength: 0.5394302317872643
  lightness: 0.19012817228212953
  saturation: 0.29562180466018617
  rhythmicContrast: 0.7075192991178483
purpose: []
